version: "3"
services:
  mongo:
    image: mongo:4
    ports:
      - "27017:27017"
    networks:
      - webnet
    volumes:
      - database:/data/db
  web:
    image: rgbtv
    ports:
      - "8080:8080"
    networks:
      - webnet
    volumes:
      - downloads:/downloads
networks:
  webnet:
volumes:
  database:
  downloads:
